#define FONT            "-*-*-medium-*-*-*-14-*-*-*-*-*-*-*"
#define UNPRESSEDBG     "#FFFFFF"
#define UNPRESSEDFG     "#2E3436"
#define PRESSEDBG       "#3584E4"
#define PRESSEDFG       "#FFFFFF"
#define DECORATIONBG    "#CDC7C2"
#define DECORATIONFG    "#E6E6E6"
#define ITEMW           130
#define ITEMB           4
#define BORDER          1
#define SEPARATOR       1
